apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: infra
  labels:
    app.kubernetes.io/part-of: chat-system
type: Opaque
stringData:
  POSTGRES_USER: chat
  POSTGRES_PASSWORD: chat-secret
