apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: apps
  labels:
    app: chat
    app.kubernetes.io/part-of: chat-system
data:
  NODE_ENV: production
  PORT: "3000"
  MESSAGING_SERVICE_URL: http://messaging-api.apps.svc.cluster.local:3004
  PRESENCE_SERVICE_URL: http://presence.apps.svc.cluster.local:3004
  REDIS_PUBSUB_URL: redis://redis.infra.svc.cluster.local:6379
