apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: apps
  labels:
    app: chat
    app.kubernetes.io/part-of: chat-system
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
    - name: http
      port: 3003
      targetPort: http
