name: chat-system-delivery

services:
  delivery-service:
    build:
      context: ./chat-system
      dockerfile: services/delivery/Dockerfile
    container_name: delivery-service
    environment:
      NODE_ENV: production
      PORT: "3005"
      REDIS_PUBSUB_URL: "${REDIS_PUBSUB_URL:-}"
      BREVO_API_KEY: "${BREVO_API_KEY:-}"
    ports:
      - "3005:3005"
      - "9234:9234"
    networks:
      - chat-network

networks:
  chat-network:
    name: chat-network
    driver: bridge
