name: chat-system-presence

services:
  redis-presence:
    image: redis:7-alpine
    container_name: presence-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - chat-network

  redis-insight:
    image: redis/redisinsight:latest
    container_name: presence-redis-insight
    ports:
      - "8001:5540"
    depends_on:
      - redis-presence
    networks:
      - chat-network

  presence-service:
    build:
      context: ./chat-system
      dockerfile: services/presence/Dockerfile
    container_name: presence-service
    environment:
      - NODE_ENV=production
      - PORT=3004
      - REDIS_PRESENCE_URL=redis://redis-presence:6379
    ports:
      - "3004:3004"
    depends_on:
      - redis-presence
    networks:
      - chat-network

networks:
  chat-network:
    name: chat-network
    driver: bridge
