name: chat-system-channel

services:
  channels-db:
    image: postgres:16-alpine
    container_name: channels-db
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat-secret
      POSTGRES_DB: channels_db
    ports:
      - "5435:5432"
    volumes:
      - channels-db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U chat -d channels_db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  channel-service:
    build:
      context: ./chat-system
      dockerfile: services/channel/Dockerfile
    container_name: channel-service
    environment:
      DB_TYPE: postgres
      DB_HOST: channels-db
      DB_PORT: "5432"
      DB_USERNAME: chat
      DB_PASSWORD: chat-secret
      DB_NAME: channels_db
      DB_SYNC: "true"
      NODE_ENV: production
      PORT: "3000"
    ports:
      - "3020:3000"
    depends_on:
      channels-db:
        condition: service_healthy
    networks:
      - chat-network

volumes:
  channels-db-data:


networks:
  chat-network:
    name: chat-network
    driver: bridge
