name: chat-system-auth

services:
  auth-service:
    build:
      context: ./chat-system
      dockerfile: services/auth/Dockerfile
    container_name: auth-service
    environment:
      DATABASE_URL: "${AUTH_DATABASE_URL:-}"
      DB_SYNC: "true"
      NODE_ENV: production
      JWT_SECRET: LSNt4suQD8N8RKq6YMGKs3ExWXsgBxrpH4XzPhZNEin
      JWT_REFRESH_SECRET: w1XZdLT1kaRv8g5ASHYPYJmYRIegXmdep70Wh40bNws
      PORT: "3001"
    ports:
      - "3002:3001"
      - "9232:9232"
    networks:
      - chat-network

networks:
  chat-network:
    name: chat-network
    driver: bridge
