apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: apps
  labels:
    app: api-gateway
    app.kubernetes.io/part-of: chat-system
type: Opaque
stringData:
  JWT_SECRET: LSNt4suQD8N8RKq6YMGKs3ExWXsgBxrpH4XzPhZNEin
