apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: apps
  labels:
    app: auth
    app.kubernetes.io/part-of: chat-system
data:
  NODE_ENV: production
  PORT: "3001"
  DB_TYPE: postgres
  DB_HOST: postgres.infra.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: users_db
  DB_SYNC: "true"
