apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: apps
  labels:
    app: auth
    app.kubernetes.io/part-of: chat-system
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: http
      port: 3001
      targetPort: http
