FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
RUN npx nx run messaging:build-worker

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/package.json /app/package-lock.json ./
COPY --from=build /app/dist/services/messaging-worker ./worker
RUN npm ci --omit=dev

ENV NODE_ENV=production
CMD ["node", "worker/main.js"]