apiVersion: v1
kind: ConfigMap
metadata:
  name: delivery-config
  namespace: apps
  labels:
    app: delivery
    app.kubernetes.io/part-of: chat-system
data:
  NODE_ENV: production
  PORT: "3005"
  REDIS_PUBSUB_URL: redis://redis.infra.svc.cluster.local:6379
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "465"
