apiVersion: v1
kind: Service
metadata:
  name: delivery
  namespace: apps
  labels:
    app: delivery
    app.kubernetes.io/part-of: chat-system
spec:
  type: ClusterIP
  selector:
    app: delivery
  ports:
    - name: http
      port: 3005
      targetPort: http
