apiVersion: v1
kind: Secret
metadata:
  name: channel-secret
  namespace: apps
  labels:
    app: channel
    app.kubernetes.io/part-of: chat-system
type: Opaque
stringData:
  DB_USERNAME: chat
  DB_PASSWORD: chat-secret
