apiVersion: v1
kind: Service
metadata:
  name: presence
  namespace: apps
  labels:
    app: presence
    app.kubernetes.io/part-of: chat-system
spec:
  type: ClusterIP
  selector:
    app: presence
  ports:
    - name: http
      port: 3004
      targetPort: http
